/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datastructureimplimentationproject;
import javax.swing.JOptionPane;

/**
 *
 * @author Ranjith
 */
public class ArrayDataStructure extends javax.swing.JFrame {
    private int arr[];
    private int size;



    /**
     * Creates new form DataStructures
     */
    public ArrayDataStructure() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bsize = new javax.swing.JButton();
        Jsize = new javax.swing.JTextField();
        TextElem = new javax.swing.JTextField();
        TextPos = new javax.swing.JTextField();
        InsertArray = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DelPos = new javax.swing.JTextField();
        DelElem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        DisplayArray = new javax.swing.JTextField();
        DisplayOutput = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        backB = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bsize.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Bsize.setText("Create");
        Bsize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsizeActionPerformed(evt);
            }
        });
        getContentPane().add(Bsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 106, -1, -1));
        getContentPane().add(Jsize, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 106, 169, -1));

        TextElem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextElemActionPerformed(evt);
            }
        });
        getContentPane().add(TextElem, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 173, 71, -1));
        getContentPane().add(TextPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 173, 71, -1));

        InsertArray.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InsertArray.setText("Insert");
        InsertArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertArrayActionPerformed(evt);
            }
        });
        getContentPane().add(InsertArray, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 173, -1, -1));

        jLabel1.setText("Element");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 176, -1, -1));

        jLabel2.setText("Position");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 176, -1, -1));

        DelPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelPosActionPerformed(evt);
            }
        });
        getContentPane().add(DelPos, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 271, 133, 23));

        DelElem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DelElem.setText("Delete");
        DelElem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelElemActionPerformed(evt);
            }
        });
        getContentPane().add(DelElem, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 271, 127, -1));

        jLabel3.setText("Position");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 274, 83, -1));
        getContentPane().add(DisplayArray, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 327, 284, 43));

        DisplayOutput.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DisplayOutput.setText("Display");
        DisplayOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayOutputActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayOutput, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 327, 107, 43));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Array DataStructure");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 210, 49));

        backB.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backB.setText("Back");
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        getContentPane().add(backB, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 398, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Data-hologram-on-a-dark-background.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 460, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DelElemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelElemActionPerformed
        // TODO add your handling code here:
        int position = Integer.parseInt(DelPos.getText());
        if(position <= arr.length - 1) {
            JOptionPane.showMessageDialog(DelPos, "Element " + arr[position] + " is Deleted At Position " + position);
            arr[position] = 0;

        }
    }//GEN-LAST:event_DelElemActionPerformed

    private void DelPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelPosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_DelPosActionPerformed

    private void InsertArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertArrayActionPerformed
        // TODO add your handling code here:

        int element = Integer.parseInt(TextElem.getText());
        int position = Integer.parseInt(TextPos.getText());
           

        if(position >= 0 && position <= arr.length - 1) {
            arr[position]  = element;
            JOptionPane.showMessageDialog(TextElem, "Element " + element + " Is Inserted to The Position " + position);
        
        }
        else {
            JOptionPane.showMessageDialog(TextElem,"Insertion not Possible Choose Number between 0 to " +  (arr.length-1) + ".","Warning",JOptionPane.WARNING_MESSAGE);
        }
        TextElem.setText("");

    }//GEN-LAST:event_InsertArrayActionPerformed

    private void TextElemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextElemActionPerformed

    }//GEN-LAST:event_TextElemActionPerformed

    private void BsizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsizeActionPerformed
        // TODO add your handling code here:

        size = Integer.parseInt(Jsize.getText());
        arr = new int[size];
        JOptionPane.showMessageDialog(Jsize,"Array of size " + size + " is Created");
    }//GEN-LAST:event_BsizeActionPerformed

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        // TODO add your handling code here:
        HomeApp app = new HomeApp();
        app.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_backBActionPerformed

    private void DisplayOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayOutputActionPerformed
        // TODO add your handling code here:
        DisplayArray.setText("");

        for(int i =0; i <= arr.length - 1; i++) {
            DisplayArray.setText(DisplayArray.getText() + arr[i] + " ");
        }
        // Clear previous display text
        

    }//GEN-LAST:event_DisplayOutputActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArrayDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArrayDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArrayDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArrayDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArrayDataStructure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bsize;
    private javax.swing.JButton DelElem;
    private javax.swing.JTextField DelPos;
    private javax.swing.JTextField DisplayArray;
    private javax.swing.JButton DisplayOutput;
    private javax.swing.JButton InsertArray;
    private javax.swing.JTextField Jsize;
    private javax.swing.JTextField TextElem;
    private javax.swing.JTextField TextPos;
    private javax.swing.JButton backB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}

