/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datastructureimplimentationproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Ranjith
 */
public class DoublyLinkedListDataStructure extends javax.swing.JFrame {

    /**
     * Creates new form DoublyLinkedListDataStructure
     */
    
    class Node {
        Node prelink;
        int data;
        Node nextlink;
    }
    Node first = null;
    public DoublyLinkedListDataStructure() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        FrontText = new javax.swing.JTextField();
        RearText = new javax.swing.JTextField();
        InsertRear = new javax.swing.JButton();
        InsertFront = new javax.swing.JButton();
        DelFront = new javax.swing.JButton();
        DelRear = new javax.swing.JButton();
        TextFront = new javax.swing.JTextField();
        TextRear = new javax.swing.JTextField();
        DisplayFront = new javax.swing.JButton();
        DisplayRear = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DoublyLinkedList DataStructure");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 17, 290, 49));

        FrontText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FrontTextActionPerformed(evt);
            }
        });
        getContentPane().add(FrontText, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 101, 82, 23));

        RearText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RearTextActionPerformed(evt);
            }
        });
        getContentPane().add(RearText, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 101, 89, 23));

        InsertRear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InsertRear.setText("Insert Rear");
        InsertRear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertRearActionPerformed(evt);
            }
        });
        getContentPane().add(InsertRear, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 101, -1, -1));

        InsertFront.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InsertFront.setText("Insert Front");
        InsertFront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertFrontActionPerformed(evt);
            }
        });
        getContentPane().add(InsertFront, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 101, -1, -1));

        DelFront.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DelFront.setText("Delete Front");
        DelFront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelFrontActionPerformed(evt);
            }
        });
        getContentPane().add(DelFront, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 185, -1, -1));

        DelRear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DelRear.setText("Delete Rear");
        DelRear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelRearActionPerformed(evt);
            }
        });
        getContentPane().add(DelRear, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 185, -1, -1));
        getContentPane().add(TextFront, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 247, 179, 50));
        getContentPane().add(TextRear, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 315, 179, 54));

        DisplayFront.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DisplayFront.setText("Display Forward");
        DisplayFront.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayFrontActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayFront, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 261, -1, -1));

        DisplayRear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DisplayRear.setText("Display Reverse");
        DisplayRear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayRearActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayRear, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 331, -1, -1));

        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 412, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Data-hologram-on-a-dark-background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 480, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertFrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertFrontActionPerformed
        // TODO add your handling code here:
                                          
    int element = Integer.parseInt(FrontText.getText());
    Node node = new Node();
    node.data = element;
    node.prelink = null;
    node.nextlink = first;

    if (first != null) {
        first.prelink = node;
    }
    first = node;

    JOptionPane.showMessageDialog(FrontText, "Element " + node.data + " is Inserted to the Front of the Linked List");

    }//GEN-LAST:event_InsertFrontActionPerformed

    private void InsertRearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertRearActionPerformed
        // TODO add your handling code here:
    int element = Integer.parseInt(RearText.getText());
    Node node = new Node();
    node.data = element;
    node.prelink = null;
    node.nextlink = null;

    if (first == null) {
        first = node;
    } else {
        Node temp = first;
        while (temp.nextlink != null) {
            temp = temp.nextlink;
        }
        temp.nextlink = node;
        node.prelink = temp;
    }

    JOptionPane.showMessageDialog(RearText, "Element " + node.data + " is Inserted at the Rear End of the Linked List");

    }//GEN-LAST:event_InsertRearActionPerformed

    private void DelRearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelRearActionPerformed
        // TODO add your handling code here:
        
        if(first == null) {
            JOptionPane.showMessageDialog(DelRear, "Deletion Not Possible Linked List Not Exists","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if(first.nextlink == null) {
            JOptionPane.showMessageDialog(DelRear, "Element " + first.data + " Got Deleted");
            first = null;
        }
        else {
            Node temp = first;
            while(temp.nextlink != null) {
                temp = temp.nextlink;
            }
            JOptionPane.showMessageDialog(DelRear, "Element " + temp.nextlink.data + " Got Deleted");
            temp.nextlink.prelink = null;
            temp.nextlink = null;

        }
    }//GEN-LAST:event_DelRearActionPerformed

    private void DelFrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelFrontActionPerformed
        // TODO add your handling code here:
        if(first == null) {
            JOptionPane.showMessageDialog(DelFront, "Deletion Not Possible Linked List Not Exixts","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if(first.nextlink == null) {
            JOptionPane.showMessageDialog(DelFront, "Element " + first.data + " Got Deleted");
            first = null;
        }
        else {
            JOptionPane.showMessageDialog(DelFront, "Element " + first.data + " Got Deleted");
            first = first.nextlink;
            first.prelink.nextlink = null;
            first.prelink = null;
        }
    }//GEN-LAST:event_DelFrontActionPerformed

    private void DisplayRearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayRearActionPerformed
    if (first == null) {
            JOptionPane.showMessageDialog(DisplayRear, "Deletion Not Possible Linked List Not Exixts","Warning",JOptionPane.WARNING_MESSAGE);
    } else {
        Node temp = first;
        TextRear.setText("");  // Clear the previous text
        while (temp != null) {
            TextRear.setText(TextRear.getText() + temp.data + " ");
            temp = temp.nextlink;
        }
    }

    }//GEN-LAST:event_DisplayRearActionPerformed

    private void DisplayFrontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayFrontActionPerformed
        // TODO add your handling code here:
    
        if (first == null) {
        JOptionPane.showMessageDialog(DisplayFront, "Display Not Possible. Linked List Does Not Exist", "Warning", JOptionPane.WARNING_MESSAGE);
    } else {
        // Traverse to the last node
        Node temp = first;
        while (temp.nextlink != null) {
            temp = temp.nextlink;
        }

        // Display from last to first
        TextFront.setText("");  // Clear previous text
        while (temp != null) {
            TextFront.setText(TextFront.getText() + temp.data + " ");
            temp = temp.prelink;
        }
}
    }//GEN-LAST:event_DisplayFrontActionPerformed

    private void RearTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RearTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RearTextActionPerformed

    private void FrontTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrontTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FrontTextActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        HomeApp app = new HomeApp();
        app.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoublyLinkedListDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoublyLinkedListDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoublyLinkedListDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoublyLinkedListDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoublyLinkedListDataStructure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton DelFront;
    private javax.swing.JButton DelRear;
    private javax.swing.JButton DisplayFront;
    private javax.swing.JButton DisplayRear;
    private javax.swing.JTextField FrontText;
    private javax.swing.JButton InsertFront;
    private javax.swing.JButton InsertRear;
    private javax.swing.JTextField RearText;
    private javax.swing.JTextField TextFront;
    private javax.swing.JTextField TextRear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
