/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datastructureimplimentationproject;

/**
 *
 * @author Ranjith
 */
public class HomeApp extends javax.swing.JFrame {

    /**
     * Creates new form HomeApp
     */
    public HomeApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BArray = new javax.swing.JButton();
        BStack = new javax.swing.JButton();
        BQ = new javax.swing.JButton();
        BcircularQ = new javax.swing.JButton();
        BSinLink = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BDouLink = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BArray.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BArray.setText("Array");
        BArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BArrayActionPerformed(evt);
            }
        });
        getContentPane().add(BArray, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 116, 114, 34));

        BStack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BStack.setText("Stack");
        BStack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BStackActionPerformed(evt);
            }
        });
        getContentPane().add(BStack, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 114, 120, 37));

        BQ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BQ.setText("Queue");
        BQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BQActionPerformed(evt);
            }
        });
        getContentPane().add(BQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 194, 114, 37));

        BcircularQ.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BcircularQ.setText("CircularQueue");
        BcircularQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcircularQActionPerformed(evt);
            }
        });
        getContentPane().add(BcircularQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 194, 120, 37));

        BSinLink.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BSinLink.setText("SinglyLinkedList");
        BSinLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSinLinkActionPerformed(evt);
            }
        });
        getContentPane().add(BSinLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 291, -1, 38));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home Page");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 41, 310, 50));

        BDouLink.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BDouLink.setText("DoublyLinkedList");
        BDouLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDouLinkActionPerformed(evt);
            }
        });
        getContentPane().add(BDouLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 291, -1, 38));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Data-hologram-on-a-dark-background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BArrayActionPerformed
        // TODO add your handling code here:
        ArrayDataStructure struct = new ArrayDataStructure();
        struct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BArrayActionPerformed

    private void BStackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BStackActionPerformed
        // TODO add your handling code here:
        StackDataStructure stack = new StackDataStructure();
        stack.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BStackActionPerformed

    private void BQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BQActionPerformed
        // TODO add your handling code here:
        QueueDataStructure queue = new QueueDataStructure();
        queue.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BQActionPerformed

    private void BcircularQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcircularQActionPerformed
        // TODO add your handling code here:
        CircularQueue queue = new CircularQueue();
        queue.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BcircularQActionPerformed

    private void BSinLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSinLinkActionPerformed
        // TODO add your handling code here:
        SinglyLinkedListDataStructure sl = new SinglyLinkedListDataStructure();
        sl.setVisible(true);
        this.dispose();
        
   
    }//GEN-LAST:event_BSinLinkActionPerformed

    private void BDouLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDouLinkActionPerformed
        // TODO add your handling code here:
        DoublyLinkedListDataStructure doubly = new DoublyLinkedListDataStructure();
        doubly.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BDouLinkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BArray;
    private javax.swing.JButton BDouLink;
    private javax.swing.JButton BQ;
    private javax.swing.JButton BSinLink;
    private javax.swing.JButton BStack;
    private javax.swing.JButton BcircularQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
