/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datastructureimplimentationproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Ranjith
 */
public class QueueDataStructure extends javax.swing.JFrame {
    private int size;
    private int queue[];
    private int front = -1;
    private int rear = -1;

    /**
     * Creates new form QueueDataStructure
     */
    public QueueDataStructure() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        TextQue = new javax.swing.JTextField();
        BCreate = new javax.swing.JButton();
        TextEnQue = new javax.swing.JTextField();
        QueueDel = new javax.swing.JButton();
        BQueDis = new javax.swing.JButton();
        QueueDis = new javax.swing.JTextField();
        QueueBack = new javax.swing.JButton();
        QueueInsert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Queue DataStructure");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 39, 210, 49));
        getContentPane().add(TextQue, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 121, 159, 30));

        BCreate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BCreate.setText("Create");
        BCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCreateActionPerformed(evt);
            }
        });
        getContentPane().add(BCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 125, -1, -1));
        getContentPane().add(TextEnQue, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 195, 159, 32));

        QueueDel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        QueueDel.setText("Delete");
        QueueDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueueDelActionPerformed(evt);
            }
        });
        getContentPane().add(QueueDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 289, 306, -1));

        BQueDis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BQueDis.setText("Display");
        BQueDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BQueDisActionPerformed(evt);
            }
        });
        getContentPane().add(BQueDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 387, -1, -1));
        getContentPane().add(QueueDis, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 376, 178, 44));

        QueueBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        QueueBack.setText("Back");
        QueueBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueueBackActionPerformed(evt);
            }
        });
        getContentPane().add(QueueBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 438, -1, -1));

        QueueInsert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        QueueInsert.setText("Insert");
        QueueInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QueueInsertActionPerformed(evt);
            }
        });
        getContentPane().add(QueueInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 204, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Data-hologram-on-a-dark-background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 480, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCreateActionPerformed
        // TODO add your handling code here:
        size = Integer.parseInt(TextQue.getText());
        queue = new int[size];
        JOptionPane.showMessageDialog(TextQue, "Queue Of Size " + size + " Is Created");
    }//GEN-LAST:event_BCreateActionPerformed

    private void QueueDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueueDelActionPerformed
        // TODO add your handling code here:
        
        if(front == queue.length - 1 && front < 0) {
            JOptionPane.showMessageDialog(QueueDel, "Queue Is Empty Deletion Not Possible","Warning", JOptionPane.WARNING_MESSAGE);
        }
        else {
            ++front;
            JOptionPane.showMessageDialog(QueueDel, "Element " + queue[front] + " Is Deleted");
        }
    }//GEN-LAST:event_QueueDelActionPerformed

    private void BQueDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BQueDisActionPerformed
        // TODO add your handling code here:
        QueueDis.setText("");
        if(front == queue.length - 1 || front < 0 && rear < 0) {
            JOptionPane.showMessageDialog(QueueDis, "Display Not Possible Queue Is Empty", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else {
            for(int i = front + 1; i <= rear; i++) {
                QueueDis.setText(QueueDis.getText() + queue[i] + " ");
            }
        }
    }//GEN-LAST:event_BQueDisActionPerformed

    private void QueueBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueueBackActionPerformed
        // TODO add your handling code here:
        HomeApp app = new HomeApp();
        app.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_QueueBackActionPerformed

    private void QueueInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QueueInsertActionPerformed
        // TODO add your handling code here:
        int element = Integer.parseInt(TextEnQue.getText());
        if(front < 0 && rear == queue.length - 1) {
            JOptionPane.showMessageDialog(TextEnQue, "Queue is Full Cannot insert the Element", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else {
            ++rear;
            queue[rear] = element;
            JOptionPane.showMessageDialog(TextEnQue, "Element " + queue[rear] + " Is Inserted in Queue At " + rear);
        }
        TextEnQue.setText("");
    }//GEN-LAST:event_QueueInsertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QueueDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QueueDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QueueDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QueueDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QueueDataStructure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCreate;
    private javax.swing.JButton BQueDis;
    private javax.swing.JButton QueueBack;
    private javax.swing.JButton QueueDel;
    private javax.swing.JTextField QueueDis;
    private javax.swing.JButton QueueInsert;
    private javax.swing.JTextField TextEnQue;
    private javax.swing.JTextField TextQue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
