/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datastructureimplimentationproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Ranjith
 */
public class SinglyLinkedListDataStructure extends javax.swing.JFrame {

    /**
     * Creates new form SinglyLinkedListDataStructure
     */
    
    class Node {
    
        int data;
        Node nextlink;
    }
    Node first;

    public SinglyLinkedListDataStructure() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        TextInsert = new javax.swing.JTextField();
        Delete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        DisplayText = new javax.swing.JTextField();
        DisplayButton = new javax.swing.JButton();
        BInsert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SinglyLinkedList DataStructure");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 31, 210, 49));
        getContentPane().add(TextInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 125, 127, -1));

        Delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Delete.setText("Delete Front");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 215, 281, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 385, -1, -1));
        getContentPane().add(DisplayText, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 283, 170, 63));

        DisplayButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DisplayButton.setText("Display");
        DisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DisplayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 303, -1, -1));

        BInsert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BInsert.setText("Insert");
        BInsert.setToolTipText("");
        BInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInsertActionPerformed(evt);
            }
        });
        getContentPane().add(BInsert, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 116, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Data-hologram-on-a-dark-background.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void BInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInsertActionPerformed
    int element = Integer.parseInt(TextInsert.getText());  // Get the element from input
    
    Node node = new Node();
    node.data = element;  // Set the data for the node
    node.nextlink = null; // The new node's nextlink should be null (end of the list)
    
    // If the list is empty, the new node becomes the first node
    if(first == null) {
        first = node;
    } else {
        // Traverse to the end of the list and insert the new node
        Node temp = first;
        while(temp.nextlink != null) {
            temp = temp.nextlink;  // Move to the next node
        }
        temp.nextlink = node;  // Add the new node at the end
    }

    // Show a message confirming the insertion
    JOptionPane.showMessageDialog(TextInsert, "Element " + node.data + " is inserted at the rear of the linked list.");
        
        TextInsert.setText("");

    }//GEN-LAST:event_BInsertActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        if(first == null) {
            JOptionPane.showMessageDialog(Delete, "Deletion Not Possible As Linked list does Exists","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else if(first.nextlink == null) {
            JOptionPane.showMessageDialog(Delete, "Element " + first.data + " Is Deleted");
            first = null;
        }
        else {
            Node temp = first;
            while(temp.nextlink.nextlink != null) {
                temp = temp.nextlink;    
            }
            JOptionPane.showMessageDialog(Delete, "Element " + temp.nextlink.data + " Is Deleted");
            temp.nextlink = null;
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void DisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayButtonActionPerformed
        // TODO add your handling code here:
      if(first == null) {
          JOptionPane.showMessageDialog(DisplayButton, "Display Not Possible, Linked List Not Exists", "Warning", JOptionPane.WARNING_MESSAGE);
      }
 else {
        Node temp = first;
            DisplayText.setText("");  // Clear the previous text
        while (temp != null) {
            DisplayText.setText(DisplayText.getText() + temp.data + " ");
            temp = temp.nextlink;
        }
    }//GEN-LAST:event_DisplayButtonActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinglyLinkedListDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinglyLinkedListDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinglyLinkedListDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinglyLinkedListDataStructure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinglyLinkedListDataStructure().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BInsert;
    private javax.swing.JButton Delete;
    private javax.swing.JButton DisplayButton;
    private javax.swing.JTextField DisplayText;
    private javax.swing.JTextField TextInsert;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
